### ISSUE TITLE
Why not tensorflow backend?

### ISSUE THREAD

**Issue by smyrbdr** [gruberto/DL-ChannelDecoding#3]
Would be awesome if you could put the tensorflow version of your codes instead of theano, especially for the use of free GPU provided by Google colaboratory. 

Currently, Google colab GPU service does not support theano backend.

**Comment by gruberto** [comment]
The code was implemented with keras, a high-level neural network that both supports theano and tensorflow. You can simply switch to tensorflow by starting the docker container with tensorflow as backend with `./run_jupyter_cpu.sh tensorflow`. However, this code was only tested with the theano backend.
