### ISSUE TITLE
Can i get the details of polar codes like which encoder and decoder have you used

### ISSUE THREAD

**Issue by Tejaswini56** [gruberto/DL-ChannelDecoding#4]

**Comment by yesmitha** [comment]
hey are you working on polar codes?

**Comment by yesmitha** [comment]
@Tejaswini56 are you working on polar codes?
I need some help,please.

**Comment by gruberto** [comment]
The details of the encoder is given in the jupyter notebook: https://github.com/gruberto/DL-ChannelDecoding/blob/master/notebooks/On%20Deep%20Learning-Based%20Channel%20Decoding.ipynb
For more details on Deep learning-based decoding, we refer to our paper: https://arxiv.org/abs/1701.07738
